//Malls
export const SET_ERRORS = "SET_ERRORS";
export const SELECTED_MALL = "SELECTED_MALL";
export const SELECTED_FLOOR = "SELECTED_FLOOR";
export const FETCH_CODING = "FETCH_CODING";
export const FETCH_STATUS = "FETCH_STATUS";
export const FETCH_MALLS = "FETCH_MALLS";
export const FETCH_FLOORS = "FETCH_FLOORS";
export const FETCH_UNITS = "FETCH_UNITS";
export const RETRIEVE_CONTRACT = "RETRIEVE_CONTRACT";
export const FETCH_DECISION_HISTORY= "FETCH_DECISION_HISTORY";
export const FETCH_DECISION_TYPES = "FETCH_DECISION_TYPES";



